### PR TITLE
add more doc-strings and type hints

### PR DESCRIPTION
**Pull request by xAspirus**

### CODE REVIEW

**Comment by CubeyTheCube** [comment]
but this has no functionality and there's no point in type hints

**Comment by xAspirus** [comment]
THERE IS A POINT IN TYPE HINTS IT ALLOWS ME TO GET SUGGESTIONS  IN VSCODE

**Comment by aspizu** [comment]
bruh

**Comment by CubeyTheCube** [comment]
> bruh

bruh

**Comment by aspizu** [comment]
i still believe you should have merged this PR

**Comment by CubeyTheCube** [comment]
> i still believe you should have merged this PR

i don't care what you believe and it's incomplete anyway

**Comment by aspizu** [comment]
autism

**Comment by CubeyTheCube** [comment]
> autism

retardation

**Pull request closed without merging**
