### PR TITLE
start docs

### LINKED ISSUE #5: m a t e r i a l for mkdocs documentation

### PR DESCRIPTION
**Pull request by FunctionalMetatable**
Resolves #5 

draft

@CubeyTheCube

### CODE REVIEW

**Comment by CubeyTheCube** [comment]
https://github.com/CubeyTheCube/scratchclient/wiki exists

**Comment by FunctionalMetatable** [comment]
> https://github.com/CubeyTheCube/scratchclient/wiki exists

nobody can contribute, only u cam

**Comment by CubeyTheCube** [comment]
@FunctionalMetatable I'm getting this error when I run the workflow:
```
Run mkdocs build --site-dir dist
  mkdocs build --site-dir dist
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.5/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.5/x64/lib
Error: MkDocs encountered an error parsing the configuration file: while parsing a block mapping
  in "/home/runner/work/scratchclient/scratchclient/mkdocs.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "/home/runner/work/scratchclient/scratchclient/mkdocs.yml", line 6, column 2
Error: Process completed with exit code 1.
```
why is this happening

**Comment by FunctionalMetatable** [comment]
it was a draft..

anyways, replace mkdocs.yml with:
```yaml
repo_url: https://github.com/CubeyTheCube/scratchclient
repo_name: CubeyTheCube/scratchclient
theme:
  name: material
  palette:
    primary: blue
  features:
    - navigation.instant
  icon:
    repo: fontawesome/brands/git-alt
    
plugins:
  - search
```

**Comment by CubeyTheCube** [comment]
> it was a draft..
I knew that, it just looked fine to me so I merged it.

Oops, I was looking at build-docs.yml instead of the correct one, that's why it wasn't fixing itself 🤦

**Comment by FunctionalMetatable** [comment]
Also, you should set the github pages branch to gh-pages in the settings for the documentation to actually appear

**Pull request merged**
